### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mysterywolf** [RTduino/RTduino#73]
## 一期目标

- [x] GPIO (数字输入输出)
- [x] ADC (模拟输入)
- [x] PWM (模拟输出)
- [x] 串口输出
- [x] Arduino通用算法库可以100%兼容
- [x] 整合RT-Thread debug输出
- [x] 软件IIC框架整合到Wire.h (未实现从机部分)
- [x] 对接Adafruit_Sensor和Adafruit_BusIO框架，以此来支持Adafruit的众多传感器库，接入Adafruit生态 
   - [x] I2C传感器
   - [x] SPI传感器
- [x] SPI
  - [x] 基本函数 
  - [ ]  legacy functions https://github.com/RTduino/RTduino/commit/be07586e7f8d9e6f7cf0428a64401139b44c2cee
- [x] 下载下来的zip文件可以直接免解压，sconscript自动处理
- [x] SerialUSB （使用TinyUSB CDC）
- [x] 梳理所有核心函数是否已经全部被实现
- [x] 完善和强化print类和stream类
- [x] analogReadResolution()
  - https://www.arduino.cc/reference/en/language/functions/zero-due-mkr-family/analogreadresolution/
- [x] analogWriteResolution() 
  - https://www.arduino.cc/reference/en/language/functions/zero-due-mkr-family/analogwriteresolution/ 
- [x] true analog DAC (潘多拉)
- [x] analogWriteFrequency()
  - https://github.com/stm32duino/wiki/wiki/API#frequency
  - https://www.stm32duino.com/viewtopic.php?f=7&t=1007
  - https://www.pjrc.com/teensy/td_pulse.html
- [x] Tone() / noTone() 函数适配

## 二期目标
- [x] __FlashStringHelper https://github.com/RTduino/RTduino/commit/fd67c9d9d567e16a03ca69e898bcf89e5d3d97d2
- [ ] analogReference() 函数适配，官方不同板子定义不一致https://www.arduino.cc/reference/en/language/functions/analog-io/analogreference/

## 三期目标
- [x] pulseIn() / pulseInLong() 函数适配 https://github.com/RTduino/RTduino/pull/10
- [x] clockCyclesPerMicrosecond() /clockCyclesToMicroseconds() / microsecondsToClockCycles()
- [x] 支持 https://github.com/GorgonMeducer/perf_counter

## 四期目标
- [x] 硬件定时器的相关库 MsTimer2
- [x] upstream https://github.com/PaulStoffregen/CapacitiveSensor
- [x] WCharaceter.h 中有两个函数是POSIX扩展函数，尚未实现 (toascii() / isascii())
- [ ] 支持从串口读取数据 （除console之外的串口，console串口不负责读数据）https://github.com/mysterywolf/RTduino/commit/d2e30acc5dc03994c5e6b1ca7d8a0b91ef55680b
- [x] https://www.arduino.cc/reference/en/language/variables/utilities/progmem/
- [x] TinyUSB 优化 https://github.com/adafruit/Adafruit_TinyUSB_Arduino/blob/master/src/arduino/Adafruit_USBD_CDC.cpp
- [x] 支持从 PWM 切换至 SPI 功能

## BSP 
- [x] 简化代码 https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32l475-atk-pandora/applications/arduino_main.cpp#L13
- [x] 补充该bsp的readme https://github.com/RT-Thread/rt-thread/tree/master/bsp/stm32/stm32l475-atk-pandora/applications/arduino_pinout
- [x] F401 板子需要测PWM
- [x] readme没有增加rtduino链接 https://github.com/RT-Thread/rt-thread/tree/master/bsp/essemi/es32f369x/applications/arduino_pinout
- [x] Bluepill BSP 适配
- [x] Raspberry PICO BSP
- [x] STM32F410 Nulceo
- [x] STM32F411 Nucleo
- [x] STM32F412 Nucleo
- [x] RT-Thread 仓库CI看护

## 文档

- [x] 增加scons --sketch= 命令的描述以及自动运行sketch宏的介绍
- [x] 增加Env+VSCode环境搭建和编译文档
- [ ] 翻译英文
- [x] doxygen文档部署

## 其他
- [x] 补充基本例程以及readme
- [x] 翻译英文
- [x] LOGO设计
- [x] 可兼容性一览表整理
- [ ] 网页设计</div>

**Comment by mysterywolf** [comment]
## Arduino库实例

- [ ] Adafruit SHT31库
- [ ] Adafruit AHTx0库
- [ ] Capacitor 库
